#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Cidade
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _cidade1;
		public virtual string Cidade1
		{
			get
			{
				return this._cidade1;
			}
			set
			{
				this._cidade1 = value;
			}
		}
		
		private string _uf;
		public virtual string Uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				this._uf = value;
			}
		}
		
		private Uf _uf1;
		public virtual Uf Uf1
		{
			get
			{
				return this._uf1;
			}
			set
			{
				this._uf1 = value;
			}
		}
		
		private IList<Pessoa> _pessoas = new List<Pessoa>();
		public virtual IList<Pessoa> Pessoas
		{
			get
			{
				return this._pessoas;
			}
		}
		
		private IList<Instituicao> _instituicaos = new List<Instituicao>();
		public virtual IList<Instituicao> Instituicaos
		{
			get
			{
				return this._instituicaos;
			}
		}
		
	}
}
#pragma warning restore 1591
