#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Comentario
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _descricao;
		public virtual string Descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				this._descricao = value;
			}
		}
		
		private long? _likes;
		public virtual long? Likes
		{
			get
			{
				return this._likes;
			}
			set
			{
				this._likes = value;
			}
		}
		
		private long? _deslikes;
		public virtual long? Deslikes
		{
			get
			{
				return this._deslikes;
			}
			set
			{
				this._deslikes = value;
			}
		}
		
		private int? _id_pessoa;
		public virtual int? Id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				this._id_pessoa = value;
			}
		}
		
		private int? _id_reclamacao;
		public virtual int? Id_reclamacao
		{
			get
			{
				return this._id_reclamacao;
			}
			set
			{
				this._id_reclamacao = value;
			}
		}
		
		private DateTime? _dataComentario;
		public virtual DateTime? DataComentario
		{
			get
			{
				return this._dataComentario;
			}
			set
			{
				this._dataComentario = value;
			}
		}
		
		private bool? _isSolucao;
		public virtual bool? IsSolucao
		{
			get
			{
				return this._isSolucao;
			}
			set
			{
				this._isSolucao = value;
			}
		}
		
		private bool? _isSolucaoFinal;
		public virtual bool? IsSolucaoFinal
		{
			get
			{
				return this._isSolucaoFinal;
			}
			set
			{
				this._isSolucaoFinal = value;
			}
		}
		
		private string _anexo;
		public virtual string Anexo
		{
			get
			{
				return this._anexo;
			}
			set
			{
				this._anexo = value;
			}
		}
		
		private Reclamacao _reclamacao;
		public virtual Reclamacao Reclamacao
		{
			get
			{
				return this._reclamacao;
			}
			set
			{
				this._reclamacao = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
		private IList<Log_participapao> _log_participapaos = new List<Log_participapao>();
		public virtual IList<Log_participapao> Log_participapaos
		{
			get
			{
				return this._log_participapaos;
			}
		}
		
	}
}
#pragma warning restore 1591
