#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Departamento
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private int? _id_instituicao;
		public virtual int? Id_instituicao
		{
			get
			{
				return this._id_instituicao;
			}
			set
			{
				this._id_instituicao = value;
			}
		}
		
		private Instituicao _instituicao;
		public virtual Instituicao Instituicao
		{
			get
			{
				return this._instituicao;
			}
			set
			{
				this._instituicao = value;
			}
		}
		
	}
}
#pragma warning restore 1591
