#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Instituicao
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _nome_fantasia;
		public virtual string Nome_fantasia
		{
			get
			{
				return this._nome_fantasia;
			}
			set
			{
				this._nome_fantasia = value;
			}
		}
		
		private string _telefone;
		public virtual string Telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private int? _id_cidade;
		public virtual int? Id_cidade
		{
			get
			{
				return this._id_cidade;
			}
			set
			{
				this._id_cidade = value;
			}
		}
		
		private string _contato;
		public virtual string Contato
		{
			get
			{
				return this._contato;
			}
			set
			{
				this._contato = value;
			}
		}
		
		private Cidade _cidade;
		public virtual Cidade Cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				this._cidade = value;
			}
		}
		
		private IList<Pessoa> _pessoas = new List<Pessoa>();
		public virtual IList<Pessoa> Pessoas
		{
			get
			{
				return this._pessoas;
			}
		}
		
		private IList<Reclamacao> _reclamacaos = new List<Reclamacao>();
		public virtual IList<Reclamacao> Reclamacaos
		{
			get
			{
				return this._reclamacaos;
			}
		}
		
		private IList<Departamento> _departamentos = new List<Departamento>();
		public virtual IList<Departamento> Departamentos
		{
			get
			{
				return this._departamentos;
			}
		}
		
	}
}
#pragma warning restore 1591
