#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Log_acesso
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime? _datahora;
		public virtual DateTime? Datahora
		{
			get
			{
				return this._datahora;
			}
			set
			{
				this._datahora = value;
			}
		}
		
		private int? _id_usuario;
		public virtual int? Id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				this._id_usuario = value;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
