#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Log_participapao
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime? _datahora;
		public virtual DateTime? Datahora
		{
			get
			{
				return this._datahora;
			}
			set
			{
				this._datahora = value;
			}
		}
		
		private int? _id_pessoa;
		public virtual int? Id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				this._id_pessoa = value;
			}
		}
		
		private int? _id_reclamacao;
		public virtual int? Id_reclamacao
		{
			get
			{
				return this._id_reclamacao;
			}
			set
			{
				this._id_reclamacao = value;
			}
		}
		
		private bool? _acesso;
		public virtual bool? Acesso
		{
			get
			{
				return this._acesso;
			}
			set
			{
				this._acesso = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private bool? _visto;
		public virtual bool? Visto
		{
			get
			{
				return this._visto;
			}
			set
			{
				this._visto = value;
			}
		}
		
		private int? _id_comentario;
		public virtual int? Id_comentario
		{
			get
			{
				return this._id_comentario;
			}
			set
			{
				this._id_comentario = value;
			}
		}
		
		private int? _id_curtidor;
		public virtual int? Id_curtidor
		{
			get
			{
				return this._id_curtidor;
			}
			set
			{
				this._id_curtidor = value;
			}
		}
		
		private Reclamacao _reclamacao;
		public virtual Reclamacao Reclamacao
		{
			get
			{
				return this._reclamacao;
			}
			set
			{
				this._reclamacao = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
		private Comentario _comentario;
		public virtual Comentario Comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				this._comentario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
