#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class ModeloBanco : OpenAccessContext, IModeloBancoUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("ModeloBanco.rlinq");
		
		public ModeloBanco()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ModeloBanco(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloBanco(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ModeloBanco(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloBanco(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<Uf> Ufs 
		{
			get
			{
				return this.GetAll<Uf>();
			}
		}
		
		public IQueryable<Pessoa> Pessoas 
		{
			get
			{
				return this.GetAll<Pessoa>();
			}
		}
		
		public IQueryable<Instituicao> Instituicaos 
		{
			get
			{
				return this.GetAll<Instituicao>();
			}
		}
		
		public IQueryable<Cidade> Cidades 
		{
			get
			{
				return this.GetAll<Cidade>();
			}
		}
		
		public IQueryable<Reclamacao> Reclamacaos 
		{
			get
			{
				return this.GetAll<Reclamacao>();
			}
		}
		
		public IQueryable<Log_acesso> Log_acessos 
		{
			get
			{
				return this.GetAll<Log_acesso>();
			}
		}
		
		public IQueryable<Comentario> Comentarios 
		{
			get
			{
				return this.GetAll<Comentario>();
			}
		}
		
		public IQueryable<Log_participapao> Log_participapaos 
		{
			get
			{
				return this.GetAll<Log_participapao>();
			}
		}
		
		public IQueryable<Pessoa_nivel_ponto> Pessoa_nivel_pontos 
		{
			get
			{
				return this.GetAll<Pessoa_nivel_ponto>();
			}
		}
		
		public IQueryable<Log_pontos_pessoa> Log_pontos_pessoas 
		{
			get
			{
				return this.GetAll<Log_pontos_pessoa>();
			}
		}
		
		public IQueryable<Departamento> Departamentos 
		{
			get
			{
				return this.GetAll<Departamento>();
			}
		}
		
		public IQueryable<Pessoa_desafio> Pessoa_desafios 
		{
			get
			{
				return this.GetAll<Pessoa_desafio>();
			}
		}
		
		public IQueryable<Desafio> Desafios 
		{
			get
			{
				return this.GetAll<Desafio>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of ModeloBanco.
		/// </summary>
		/// <param name="config">The BackendConfiguration of ModeloBanco.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IModeloBancoUnitOfWork : IUnitOfWork
	{
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<Uf> Ufs
		{
			get;
		}
		IQueryable<Pessoa> Pessoas
		{
			get;
		}
		IQueryable<Instituicao> Instituicaos
		{
			get;
		}
		IQueryable<Cidade> Cidades
		{
			get;
		}
		IQueryable<Reclamacao> Reclamacaos
		{
			get;
		}
		IQueryable<Log_acesso> Log_acessos
		{
			get;
		}
		IQueryable<Comentario> Comentarios
		{
			get;
		}
		IQueryable<Log_participapao> Log_participapaos
		{
			get;
		}
		IQueryable<Pessoa_nivel_ponto> Pessoa_nivel_pontos
		{
			get;
		}
		IQueryable<Log_pontos_pessoa> Log_pontos_pessoas
		{
			get;
		}
		IQueryable<Departamento> Departamentos
		{
			get;
		}
		IQueryable<Pessoa_desafio> Pessoa_desafios
		{
			get;
		}
		IQueryable<Desafio> Desafios
		{
			get;
		}
	}
}
#pragma warning restore 1591
