#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Pessoa_desafio
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _idPessoa;
		public virtual int? IdPessoa
		{
			get
			{
				return this._idPessoa;
			}
			set
			{
				this._idPessoa = value;
			}
		}
		
		private int? _idDesafio;
		public virtual int? IdDesafio
		{
			get
			{
				return this._idDesafio;
			}
			set
			{
				this._idDesafio = value;
			}
		}
		
		private bool? _ganho;
		public virtual bool? Ganho
		{
			get
			{
				return this._ganho;
			}
			set
			{
				this._ganho = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private DateTime? _hora;
		public virtual DateTime? Hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				this._hora = value;
			}
		}
		
		private int? _vezesGanhas;
		public virtual int? VezesGanhas
		{
			get
			{
				return this._vezesGanhas;
			}
			set
			{
				this._vezesGanhas = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
		private Desafio _desafio;
		public virtual Desafio Desafio
		{
			get
			{
				return this._desafio;
			}
			set
			{
				this._desafio = value;
			}
		}
		
	}
}
#pragma warning restore 1591
