#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Pessoa
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _apelido;
		public virtual string Apelido
		{
			get
			{
				return this._apelido;
			}
			set
			{
				this._apelido = value;
			}
		}
		
		private DateTime? _data_nascimento;
		public virtual DateTime? Data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				this._data_nascimento = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _telefone;
		public virtual string Telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		
		private string _descricao;
		public virtual string Descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				this._descricao = value;
			}
		}
		
		private string _avatar;
		public virtual string Avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				this._avatar = value;
			}
		}
		
		private System.Nullable<System.Char> _tipo;
		public virtual System.Nullable<System.Char> Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private int? _id_cidade;
		public virtual int? Id_cidade
		{
			get
			{
				return this._id_cidade;
			}
			set
			{
				this._id_cidade = value;
			}
		}
		
		private System.Nullable<System.Char> _isAtivo;
		public virtual System.Nullable<System.Char> IsAtivo
		{
			get
			{
				return this._isAtivo;
			}
			set
			{
				this._isAtivo = value;
			}
		}
		
		private int? _id_instituicao;
		public virtual int? Id_instituicao
		{
			get
			{
				return this._id_instituicao;
			}
			set
			{
				this._id_instituicao = value;
			}
		}
		
		private Instituicao _instituicao;
		public virtual Instituicao Instituicao
		{
			get
			{
				return this._instituicao;
			}
			set
			{
				this._instituicao = value;
			}
		}
		
		private Cidade _cidade;
		public virtual Cidade Cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				this._cidade = value;
			}
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios
		{
			get
			{
				return this._usuarios;
			}
		}
		
		private IList<Reclamacao> _reclamacaos = new List<Reclamacao>();
		public virtual IList<Reclamacao> Reclamacaos
		{
			get
			{
				return this._reclamacaos;
			}
		}
		
		private IList<Comentario> _comentarios = new List<Comentario>();
		public virtual IList<Comentario> Comentarios
		{
			get
			{
				return this._comentarios;
			}
		}
		
		private IList<Log_participapao> _log_participapaos = new List<Log_participapao>();
		public virtual IList<Log_participapao> Log_participapaos
		{
			get
			{
				return this._log_participapaos;
			}
		}
		
		private IList<Pessoa_nivel_ponto> _pessoa_nivel_pontos = new List<Pessoa_nivel_ponto>();
		public virtual IList<Pessoa_nivel_ponto> Pessoa_nivel_pontos
		{
			get
			{
				return this._pessoa_nivel_pontos;
			}
		}
		
		private IList<Log_pontos_pessoa> _log_pontos_pessoas = new List<Log_pontos_pessoa>();
		public virtual IList<Log_pontos_pessoa> Log_pontos_pessoas
		{
			get
			{
				return this._log_pontos_pessoas;
			}
		}
		
		private IList<Pessoa_desafio> _pessoa_desafios = new List<Pessoa_desafio>();
		public virtual IList<Pessoa_desafio> Pessoa_desafios
		{
			get
			{
				return this._pessoa_desafios;
			}
		}
		
	}
}
#pragma warning restore 1591
