#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Pessoa_nivel_ponto
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _id_pessoa;
		public virtual int? Id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				this._id_pessoa = value;
			}
		}
		
		private int? _nivel;
		public virtual int? Nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				this._nivel = value;
			}
		}
		
		private long? _pontos;
		public virtual long? Pontos
		{
			get
			{
				return this._pontos;
			}
			set
			{
				this._pontos = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
	}
}
#pragma warning restore 1591
