#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Reclamacao
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _descricao;
		public virtual string Descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				this._descricao = value;
			}
		}
		
		private string _titulo;
		public virtual string Titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				this._titulo = value;
			}
		}
		
		private bool? _isSolucionado;
		public virtual bool? IsSolucionado
		{
			get
			{
				return this._isSolucionado;
			}
			set
			{
				this._isSolucionado = value;
			}
		}
		
		private string _departamento;
		public virtual string Departamento
		{
			get
			{
				return this._departamento;
			}
			set
			{
				this._departamento = value;
			}
		}
		
		private int? _id_instituicao;
		public virtual int? Id_instituicao
		{
			get
			{
				return this._id_instituicao;
			}
			set
			{
				this._id_instituicao = value;
			}
		}
		
		private int? _id_pessoa;
		public virtual int? Id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				this._id_pessoa = value;
			}
		}
		
		private int? _likes;
		public virtual int? Likes
		{
			get
			{
				return this._likes;
			}
			set
			{
				this._likes = value;
			}
		}
		
		private int? _deslikes;
		public virtual int? Deslikes
		{
			get
			{
				return this._deslikes;
			}
			set
			{
				this._deslikes = value;
			}
		}
		
		private string _anexo;
		public virtual string Anexo
		{
			get
			{
				return this._anexo;
			}
			set
			{
				this._anexo = value;
			}
		}
		
		private DateTime? _dataHora;
		public virtual DateTime? DataHora
		{
			get
			{
				return this._dataHora;
			}
			set
			{
				this._dataHora = value;
			}
		}
		
		private bool? _isAtivo;
		public virtual bool? IsAtivo
		{
			get
			{
				return this._isAtivo;
			}
			set
			{
				this._isAtivo = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
		private Instituicao _instituicao;
		public virtual Instituicao Instituicao
		{
			get
			{
				return this._instituicao;
			}
			set
			{
				this._instituicao = value;
			}
		}
		
		private IList<Comentario> _comentarios = new List<Comentario>();
		public virtual IList<Comentario> Comentarios
		{
			get
			{
				return this._comentarios;
			}
		}
		
		private IList<Log_participapao> _log_participapaos = new List<Log_participapao>();
		public virtual IList<Log_participapao> Log_participapaos
		{
			get
			{
				return this._log_participapaos;
			}
		}
		
	}
}
#pragma warning restore 1591
