#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Ouvidoria_Social_DataAccess;

namespace Ouvidoria_Social_DataAccess	
{
	public partial class Usuario
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _login;
		public virtual string Login
		{
			get
			{
				return this._login;
			}
			set
			{
				this._login = value;
			}
		}
		
		private string _senha;
		public virtual string Senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				this._senha = value;
			}
		}
		
		private int? _id_pessoa;
		public virtual int? Id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				this._id_pessoa = value;
			}
		}
		
		private bool? _gamify;
		public virtual bool? Gamify
		{
			get
			{
				return this._gamify;
			}
			set
			{
				this._gamify = value;
			}
		}
		
		private Pessoa _pessoa;
		public virtual Pessoa Pessoa
		{
			get
			{
				return this._pessoa;
			}
			set
			{
				this._pessoa = value;
			}
		}
		
		private IList<Log_acesso> _log_acessos = new List<Log_acesso>();
		public virtual IList<Log_acesso> Log_acessos
		{
			get
			{
				return this._log_acessos;
			}
		}
		
	}
}
#pragma warning restore 1591
